### ISSUE TITLE
Misplacement of table 1 

### ISSUE THREAD

**Issue by hpvd** [gucci-on-fleek/lua-widow-control#25]
### Issue

In doc of v2.0.0:

Table 1 contains a visual demonstration,
but it is placed before the section "Demonstration"
If you use 
- in the pdf in the TOC the link to Demonstration
- or the pdf bookmark Demonstration shown in PDF reader,

 you may miss this great visual explanation.

### Expected Behavior

Having table 1 within / as part of section "Demonstration"

**Comment by hpvd** [comment]
possibly related to this:

the page with table 1
- seems to be excluded from page numbering
- seems to have a different page format (not only landscape)

both may make printing of document harder (yes there are people around who really still do this ;-)

![2022-03-09_13h50_51](https://user-images.githubusercontent.com/5681880/157446676-3164c3a7-7bb5-4834-ab21-1abb971c614d.png)

**Comment by gucci-on-fleek** [comment]
Well, the root of the problem here is that the table is too big to fit on portrait letter paper. 

1. If I scale down the table so that it fits, it gets _really_ small. 

1. I've also tried reshaping the table so that it fits on portrait letter paper:
    <details><summary>View Image</summary>
    <img src="https://user-images.githubusercontent.com/49086429/157799261-1997957c-6396-465c-bb7c-e5d7b6ca4947.png"/>
    </details>

    This works okay, but its much harder to scan across the the table and see the differences.
1. I can leave the table on its own landscape page, like it is right now.

So I think that having the big landscape table like it is is _probably_ the best solution, although I'm open to suggestions otherwise.

## Section Heading

I agree that the section heading relative to the table isn't great, but I'm not sure of any better alternatives.

1. I could have just the section head on the page before the table. 
    <details><summary>View Image</summary>
    <img src="https://user-images.githubusercontent.com/49086429/157800192-2b76dd3d-e870-4529-a4cb-8593848b40ac.png"/>
    </details>
    
    But then you get a big blank right after the section heading which looks pretty bad.

1. I could put the section heading on the same page as the table.
    <details><summary>View Image</summary>
    <img src="https://user-images.githubusercontent.com/49086429/157800656-4824cd8c-1e45-43af-9d0d-2eef4359b9a4.png"/>
    </details>

    This kinda works. The problem here is that it looks like the heading is only for the table, and not for the whole section that follows.

1. I could leave it the same way that it is now.
1. I could move the table to go _after_ the words/description. The problem is that people naturally read top to bottom, and the words/description doesn't make much sense without reading the table first. 

Option 1 is a bad idea, but options 2–4 are pretty feasible. 

## Printing

The document should usually print fine, even with the sideways table. This is viewer-dependent, but printing to PDF from Firefox gives you this:
<details><summary>View Image</summary>
<img src="https://user-images.githubusercontent.com/49086429/157802217-f1168eb8-bc25-468b-83ba-3e68836f973f.png"/>
</details>
which I think is pretty good. Adobe Acrobat gives similar results, so I think that this is fine.

## Page Numbers

Hmm, the page with the table on it should be numbered (`pagestate=start`)

https://github.com/gucci-on-fleek/lua-widow-control/blob/d8b05f546d402ca8570e46022751a9212682a6cd/docs/lwc-documentation.tex#L99-L105

but it clearly isn't. I'll try and fix this.

**Comment by gucci-on-fleek** [comment]
This implements #&zwnj;4 from above.

https://github.com/gucci-on-fleek/lua-widow-control/releases/download/release-8daebc73bdfac596a46f8867748bae5a416194f3/lua-widow-control.pdf

This looks alright to me, so I'll probably merge it in. Let me know what you think.

**Comment by hpvd** [comment]
landscape is totally fine. Was only wondering why the landscape page has a different format (lenght->width) than the portrait pages. This may irritate printers...

your fix regarding page numbering seems not to be included yet?

**Comment by hpvd** [comment]
ah just saw the fix for page numbering was added later...
