### ISSUE TITLE
enhance visual quality further with microtype package

### ISSUE THREAD

**Issue by hpvd** [gucci-on-fleek/lua-widow-control#3]
Awesome package! Many thanks for your work!
Would be interesting to see in Doc/Table 1: A visual comparison a 5th column:
"lua widow control in combination with microtype package" (https://github.com/schlcht/microtype/)

Making this work, the visual experience should possibly be further improved while generating the needed text length not only between words but also within words.

> Micro-typography is the art of enhancing the appearance and readability of a
> document while exhibiting a minimum degree of visual obtrusion. It is concerned
> with what happens between or at the margins of characters, words or lines. 

https://ctan.org/pkg/microtype?lang=en

**Comment by gucci-on-fleek** [comment]
Microtype is already enabled by default in lua-widow-control. Without it, lua-widow-control would still work, but it would tend to produce pretty poor results.

https://github.com/gucci-on-fleek/lua-widow-control/blob/8d1228bf1697e2720062b0c2a40f306005da72e8/source/lua-widow-control.sty#L22-L25

---

Now, you did manage to catch a small bug in the documentation. I thought that I had enabled font expansion in the comparison table at

https://github.com/gucci-on-fleek/lua-widow-control/blob/8d1228bf1697e2720062b0c2a40f306005da72e8/docs/lwc-sample.tex#L31-L32

However, it looks like it requires some special font commands to make expansion/protrusion work correctly with Latin Modern. This should be fixed in 6c1492ad749482f8ff8e826ac484f34e813c676d, so all of the table columns should have expansion/protrusion enabled.

---

Here's a comparison of the demo table with and without protrusion/expansion. 

![animated](https://user-images.githubusercontent.com/49086429/152470559-f85d6f65-7418-44d3-9996-b7c03aa86237.png)

**Comment by gucci-on-fleek** [comment]
The demo table should be fixed in [v1.1.4](https://github.com/gucci-on-fleek/lua-widow-control/releases/tag/release-a8caba8e689ce5c743a88dcf1dcd8e4a0db67fb2). It should be in TeX Live in ~12–24 h.

**Comment by hpvd** [comment]
yeah, looks much better :-)

**Comment by hpvd** [comment]
When intensively looking at the example, the visual quality is not as quite perfect as usual when using microtype package with default settings in combination with latex default font.

Maybe one should give it a try without having to do manual optimizing settings of font and microtype package further...

**Comment by hpvd** [comment]
in addition to testing what is possible with defaults (font and microtype setting)
which would also meet the most basic level where users start/what they expect

one may even thing further and rely soley on microtype to distribute and modify characters and spaces within the given needed length... https://github.com/gucci-on-fleek/lua-widow-control/issues/4
